---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rates-pod
  labels:
    app: rates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rates
  template:
    metadata:
      labels:
        app: rates
    spec:
      containers:
        - name: rates
          image: billystack/sm-rates:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "kubernetes"
        - name: redis-server
          image: redis
          ports:
            - containerPort: 6379